### ISSUE TITLE
Ontology_class prototype

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-cp/ontology#1]
I recommend we show here an `Ontology_class` prototype in a (at least I think) universally agreed upon format:

From __schema_blocks__, written in _YAML_:

```
  Ontology_class
    properties:
      id:
        description: properly prefixed CURIE of the ontology term
        type: string
        example: 'ncit:C8294'
      label:
        description: the text label associated with the term
        type: string
        example: 'Pancreatic Adenocarcinoma'
```

From __phenopackets__, written in _ProtocolBuffers_:

```
// A class (aka term, concept) in an ontology.
message OntologyClass {
    // a CURIE-style identifier e.g. HP:0100024, MP:0001284, UBERON:0001690.
    // This is the primary key for the ontology class
    string id = 1;
    
    // class label, aka name. E.g. "Abnormality of cardiovascular system"
    string label = 2;
}
```
